### ISSUE TITLE
Comma/Semicolon secret

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#121] opened 2021-03-01 14:07 UTC
Image content – free field would be better here. Matija discovered that the problem is happening when there are commas. Commas create separate entities (this can be fixed through ‘navigate’), but it can be created by adding a semicolon at the end of the sentence/text.

**Comment by Mergpijp** [comment] 2021-03-01 14:37
Image content is a charfield already does it need its own model so It can be editied through navigate?

**Comment by Woseseltops** [comment] 2021-03-05 14:34
I think this is a duplicate of #113 , right? If you agree @Elisagig , please close this issue :) .

If #113 is not live yet, it will be deployed at the end of sprint sprint 1 ( https://github.com/Mergpijp/GlobalOrthodoxy/milestone/1 ) .

**Closed** 2021-03-09 11:51 UTC
