### ISSUE TITLE
Bug in image content field: text is letter by letter with commas 

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#91] opened 2020-10-20 10:37 UTC
From my colleague Matija
"There is bug in the image content field - it is possible to add but when you view the publication, the text is like letter by letter, with commas between the letters"

**Comment by Woseseltops** [comment] 2020-10-23 10:18
I indeed also discovered this in #71, but it is not picked yet. I've closed that one now so we can continue here.

**Comment by Mergpijp** [comment] 2020-11-06 13:34
This is strange ive tried to reproduce this but it seems fine. Can you link to the globalorthodoxy view were this issue persists?

**Comment by Mergpijp** [comment] 2020-11-06 13:42
Okay I have discovered occurence in detail view. But when I look at image contents I can see lots of entries with one letter. Sure you have added the correct image content?

**Comment by Elisagig** [comment] 2020-11-06 13:44
What do you mean by "with one letter"?

**Comment by Mergpijp** [comment] 2020-11-06 13:50
Well I have looked at the code and it puts commas between entries of image contents (linked to the file). But if you take a closer look at the image content entries for all files availible there are one letter entries.

[here](https://globalorthodoxy.cls.ru.nl/imagecontent/show/?page=5&order_by=&direction=)

**Comment by Elisagig** [comment] 2020-11-06 13:52
Oh that is weird. I will let my team know.

**Comment by Mergpijp** [comment] 2020-11-06 13:52
Oh right it might be a bug with my comma seperated entry for image contents will check

**Comment by Mergpijp** [comment] 2020-11-06 13:55
So I tried reproducing this by adding a image content to a uploaded file. Just enter something new and press enter. Seems to work fine.

**Comment by Elisagig** [comment] 2020-11-06 13:56
Ok so I close it now?

**Comment by Mergpijp** [comment] 2020-11-06 13:58
No keep it open there might be something I overlooked

**Comment by Mergpijp** [comment] 2020-11-06 13:59
Because if you read what i just send you. There are clearly words formed letter by letter. No idea how they did that.

**Comment by Elisagig** [comment] 2020-11-06 13:59
My colleague Matija just said the following: 
"The field itself is a bit weird because it's neither an open text field (like content description) neither an entry field (where you have to add something first, like that of special occasions for example)"

**Comment by Mergpijp** [comment] 2020-11-06 14:04
Yes it is one of the few Select2TagWidgets were you can make your own tags in the bar and press enter to add a new tag. It is more dynamic as requested.

**Comment by Elisagig** [comment] 2020-11-06 14:05
Ok I see

**Comment by Elisagig** [comment] 2020-11-06 14:23
I send a screenshot of what my colleague is saying

**Comment by Elisagig** [comment] 2020-11-06 14:24
![20201106_151905](https://user-images.githubusercontent.com/61408472/98376746-368ce380-2044-11eb-8bf1-d228270b1083.jpg)

**Comment by Mergpijp** [comment] 2020-11-06 14:37
Then the follow-up question would be: Is he using commas to seperate entries? Or enters? Because I think enters are now configured as seperator.

**Comment by Elisagig** [comment] 2020-11-06 14:40
Just asked him. Will keep you updated

**Comment by Elisagig** [comment] 2020-11-06 15:10
He says "Enters" and that it is working ok now

**Comment by Woseseltops** [comment] 2020-11-13 09:36
Just for clarity, so we figured out it works when you use enters (also: semicolons) to separate image contents. Did Matija also use enters as separators before, meaning that the problem is now fixed? Or did he use something else before, and did he now learn that he can avoid the problem using enters? If the former case, can you close the issue @Elisagig ? In the latter case, what was he using before?

**Comment by Elisagig** [comment] 2020-11-16 09:44
Message from my colleague Matija about this:
"I used space as separators (in a sentence) and it gives separate letters with commas as a result. We want to be able to write a whole sentence in this field, not only separate words.
A strange thing happened when we tried it during the meeting - the first time it didn't work (it didn't show the image content we entered) or it worked only when we chose an already-existing entry from the list. For me it worked last week (adding a sentence, separating it normally with spaces), but as we could see during the meeting today it didn't work"

**Comment by Woseseltops** [comment] 2020-11-20 14:12
Hmm okay, for me it exactly works as I'd expect, so it looks like we are not doing the same thing. Perhaps you can show me next Friday?

**Comment by Elisagig** [comment] 2020-11-23 08:58
Prima. Ik ga het ook aan Matija doorgeven

**Comment by Elisagig** [comment] 2020-11-23 09:09
Ok Matija is saying the following:

Matija: "Yes, he's right, we do hit the 'enter' after writing a sentence, and it shows as a tag to be selected. I select it and so far there's no problem. But at the end, when you see the publication, image content is like what we reported earlier - letters separated by commas. I will check again how it is today"

Matija: "It's not working. So there are 2 problems"

He will send me the explanation when he is free

**Comment by Mergpijp** [comment] 2021-01-20 15:17
Dear all I have been trying to reproduce this with limited succes. Problem 1 was a typo on my side and works with the new version of globalorthodoxy. Problem 2 I tried typing long sentences with spaces (between words) and enter when done. And if i go to image content it is displayed normally. I cannot reproduce the problem I am sorry. Maybe we can meet in zoom for this?

**Comment by Woseseltops** [comment] 2021-01-21 13:30
Hey @Mergpijp I actually already planned a 10 minute meeting with Matija about this and I can now reproduce. The steps:

1. Create a new publication and go to UploadedFiles
2. Add a title, category and actually upload a file
3. For image content, type something which does NOT exist yet, and click the dropdown to 'finish' (note: typing a semicolon also works and gives the same problem).
4. Save the uploaded file and the publicationi
5. Look up the UploadedFile in the list of UploadedFiles

**Comment by Elisagig** [comment] 2021-01-22 14:07
Good to know. Thanks.  Let me know when resolved

**Comment by Woseseltops** [comment] 2021-01-22 14:17
Working plan as discussed. Emmanuel:
* brings his local version back to what is on the server
* try to reproduce
* fix
* deploy

**Comment by Elisagig** [comment] 2021-01-22 14:22
Thanks!

**Comment by Mergpijp** [comment] 2021-01-22 15:17
I am having difficulties reproducing. I use the newest version were you can add uploadedfiles directly to publication (create). 
And it works what am i doing good?

**Comment by Mergpijp** [comment] 2021-01-22 15:54
So somehow when uploading a file the values of the image content tags are different. It becomes a string seperated by commas. So never use commas please. Now I make it a list split by commas. And it seems to work. Also added the code for keywords. Deploying now.

**Closed** 2021-01-29 14:06 UTC
Labels: high prio
